# -*- coding: utf-8 -*-
"""AI_Lab_7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_f4cjax-nxRyZuzYSm2It_KciIy3ee_B

## Image Segmentation
"""

#Mount Google drive to read the files from
from google.colab import drive

!pip install pixellib
import pixellib
from pixellib.instance import instance_segmentation
import cv2
from google.colab.patches import cv2_imshow

import torch
import pixellib
from pixellib.torchbackend.instance import instanceSegmentation

model = instanceSegmentation()
model.load_model("pointrend_resnet50.pkl")
segmask, output = model.segmentImage("Image_Segmentation_2.png", show_bboxes=True)
cv2_imshow(output)

"""##Discussion

Image segmentation performs well on the current objects in the image, but it needs to be tested on images with a higher number of objects to evaluate its accuracy.

##Application of Image Segmentation for another image
"""

#Mount Google drive to read the files from
from google.colab import drive

!pip install pixellib
import pixellib
from pixellib.instance import instance_segmentation
import cv2
from google.colab.patches import cv2_imshow

import torch
import pixellib
from pixellib.torchbackend.instance import instanceSegmentation

model = instanceSegmentation()
model.load_model("pointrend_resnet50.pkl")
segmask, output = model.segmentImage("Image_Segmentation_3png.jpg", show_bboxes=True)
cv2_imshow(output)

"""##Discussion

Image segmentation demonstrates robust performance across images containing numerous objects, accurately predicting and delineating regions for a wide variety of objects present within the image.
"""