# -*- coding: utf-8 -*-
"""AI_Lab_7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VXsaj3PHvEMf8xbuiU3HmrlSKWM9n48i

##Object Recognition Using YOLO
"""

!pip install cvlib
import cvlib
from cvlib.object_detection import draw_bbox, YOLO

# The default YOLO model files
config = 'yolov3.cfg'
weights = 'yolov3.weights'
labels = 'yolov3.txt'

# # Alternative the "tiny" version of YOLO, which is faster but less accurate
# config = path + 'yolov3-tiny.cfg'
# weights = path + 'yolov3-tiny.weights'
# labels = path + 'yolov3.txt'

# Construct the YOLOv3 Model
yolo = YOLO(weights, config, labels)

import cv2
from google.colab.patches import cv2_imshow

# Read an image file
img = cv2.imread('Object_Detection_1.jpg')
# img = cv2.imread(path+'objects2.jpg')
cv2_imshow(img)
print()

# Detect objects from the image, and display the results
bbox, label, conf = yolo.detect_objects(img)
# bbox, label, conf = yolo.detect_objects(img, confidence=0.25, nms_thresh=0.2)
yolo.draw_bbox(img, bbox, label, conf)
cv2_imshow(img)

"""##Discussion

The pre-trained YOLO model performs well with high accuracy. From the object detection results, we can see that nearly all objects are identified. Additionally, it even detects the partial image of a man that is not fully captured in the frame.

##Object detection for another Image
"""

!pip install cvlib
import cvlib
from cvlib.object_detection import draw_bbox, YOLO

# The default YOLO model files
config = 'yolov3.cfg'
weights = 'yolov3.weights'
labels = 'yolov3.txt'

# # Alternative the "tiny" version of YOLO, which is faster but less accurate
# config = path + 'yolov3-tiny.cfg'
# weights = path + 'yolov3-tiny.weights'
# labels = path + 'yolov3.txt'

# Construct the YOLOv3 Model
yolo = YOLO(weights, config, labels)

import cv2
from google.colab.patches import cv2_imshow

# Read an image file
img = cv2.imread('Object_Detection_2.jpg')
# img = cv2.imread(path+'objects2.jpg')
cv2_imshow(img)
print()

# Detect objects from the image, and display the results
bbox, label, conf = yolo.detect_objects(img)
# bbox, label, conf = yolo.detect_objects(img, confidence=0.25, nms_thresh=0.2)
yolo.draw_bbox(img, bbox, label, conf)
cv2_imshow(img)

"""##Discussion

The pre-trained yolo model works good with better accuracy. From the above object detection we can observe that most of all the objects are detected, but the dog which is brown in colour is not detected. Here the model either fails to detect that particular object or considers it along with the next dog as a whole object.
"""