# -*- coding: utf-8 -*-
"""AI_Lab_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F2nAeTuA4NxNpqYtLDOmBavdihCWuBKs

##Topic Modelling
"""

import nltk
from nltk.corpus import stopwords
from nltk.stem.snowball import SnowballStemmer
from gensim import models, corpora

documents = [
  """
  Artificial intelligence (AI), sometimes called machine
  intelligence, is intelligence demonstrated by machines, unlike
  the natural intelligence displayed by humans and animals. Leading
  AI textbooks define the field as the study of "intelligent
  agents": any device that perceives its environment and takes
  actions that maximize its chance of successfully achieving its
  goals. Colloquially, the term "artificial intelligence" is often
  used to describe machines (or computers) that mimic "cognitive"
  functions that humans associate with the human mind, such
  as "learning" and "problem solving".
  """,
  """
  Association football, more commonly known as football or
  soccer, is a team sport played with a spherical ball between
  two teams of 11 players. It is played by approximately 250
  million players in over 200 countries and dependencies, making it
  the world's most popular sport. The game is played on a
  rectangular field called a pitch with a goal at each end. The
  object of the game is to outscore the opposition by moving the
  ball beyond the goal line into the opposing goal. The team with
  the higher number of goals wins the game.
  """
]

# Clean the data by using stemming and stopwords removal
nltk.download('stopwords')
stemmer = SnowballStemmer('english')
stop_words = stopwords.words('english')
texts = [
  [stemmer.stem(word) for word in document.lower().split() if word not in stop_words]
  for document in documents
  ]

# Create a dictionary from the words
dictionary = corpora.Dictionary(texts)

# Create a document-term matrix
doc_term_mat = [dictionary.doc2bow(text) for text in texts]

# Generate the LDA model
num_topics = 2
ldamodel = models.ldamodel.LdaModel(doc_term_mat,
        num_topics=num_topics, id2word=dictionary, passes=25)

num_words = 5
for i in range(num_topics):
  print(ldamodel.print_topic(i, topn=num_words))

print('\nTop ' + str(num_words) + ' contributing words to each topic:')
for item in ldamodel.print_topics(num_topics=num_topics, num_words=num_words):
    print('\nTopic', item[0])
    list_of_strings = item[1].split(' + ')
    for text in list_of_strings:
        details = text.split('*')
        print("%-12s:%0.2f%%" %(details[1], 100*float(details[0])))

new_docs = [
  """
  Jager thinks this is just the start of AI eating the beautiful
  game. “We have a dedicated team that focuses only on artificial
  intelligence and machine learning for sports teams,” he
  says. “That is not only for soccer, but for Formula One and
  American football. We have a baseball team, and we're talking
  right now with cricket teams.”
  """
]

new_texts = [
  [stemmer.stem(word) for word in document.lower().split() if word not in stop_words]
  for document in new_docs
  ]
new_doc_term_mat = [dictionary.doc2bow(text) for text in new_texts]

vector = ldamodel[new_doc_term_mat]
print(vector[0])

"""##Discussion

Model is trained on some of the words in Topic 0 which is related to artificial intelligence and some of the words in Topic 1 which is related to football.

While testing we can see in the result that

In Topic 0,below are the pecentages of words that are matching words of artificial intelligence

human - 3.50, intellig - 3.50, machin - 2.50, field - 1.50, associ - 1.50.

In Topic 1,below are the pecentages of words that are matching words of football

play - 3.60%, team - 3.60%, goal - 3.60%, game - 2.60%, ball - 2.60%


The new document is also tested for the same model. We can assert from the programming output that it has 50.67% of the words that matches the words with artificial intelligence topic and 49.32% of the words that matches the words with football topic.
"""